print('Olá, cadastre-se aqui.')
nome = input('Nome:')
sobrenome = input('Sobrenome:')
print('Agora a data de nascimento:')
dia = input('dia:')
mes = input('mes:')
ano = input('ano:')
print('Muito bem, agora o email e senha:')
EMAIL = input('EMAIL:')
SENHA = input('SENHA:')
print('LOGADO COM SUCESSO*')
print('BEM VINDO(a) AO FACEBOOK' , nome , '!')
