nome = input('Qual é o seu nome?')
print(f'BEM VINDO(A) {nome} !')
idade = input('Quantos anos você tem?')
peso = float(input('Quanto você pesa?'))
print(f'Suas informaçoes são,\n {nome}, \n {idade} anos, \n {peso} kg')
