print('Olá, cadastre-se aqui.')
print('Primeiro preencha as informações abaixo:')
nome = input('Nome:')
b = input('Sobrenome:')
print('Agora a data de nascimento:')
c = input('dia:')
d = input('mes:')
e = input('ano:')
print('Muito bem, agora o email e senha:')
f = input('EMAIL:')
g = input('SENHA:')
print('LOGADO COM SUCESSO*')
print('Agora aproveite sua conta no FaceBook' , nome , '!')

