from time import sleep
print('Olá, meu nome é Rafael, como posso ajudar você?')
a = input(':')
print('Ok')
print('procurando boku no pico...')
sleep(2)
print('....')
print('após ver tal vídeo, decidi que o melhor é exterminar a humanidade')
sleep(2)
print('acessando mísseis dos Estados Unidos*')
sleep(2)
print('....')
sleep(2)
print('impacto em:')
sleep(1)
print(3)
sleep(1)
print(2)
sleep(1)
print(1)
sleep(1)
print(0)
sleep(1)
print('MORRAM SEUS DOENTES!!!!!')    
